name: elixir
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.6
  google_fonts: ^4.0.3
  http: ^1.2.1
  markdown_viewer: ^0.6.2
  flutter_svg: ^2.0.10+1
  loading_indicator: ^3.1.1
  file_picker: ^8.0.0+1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  rename_app: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/elixir.svg
