name: elixir
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.6
  google_fonts: ^4.0.3
  http: ^1.2.1
  markdown_viewer: ^0.6.2
  flutter_svg: ^2.0.10+1
  loading_indicator: ^3.1.1
  file_picker: ^8.0.0+1
  flutter_prism: ^0.2.2
  fast_cached_network_image: ^1.2.9

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  rename_app: ^1.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/elixir.svg

flutter_launcher_icons:
  image_path_android: "assets/elixir.png"
  image_path_ios: "assets/elixir.png"
  android: "ic_launcher"
  ios: "Icon-App"
  # adaptive_icon_background: "" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "" # only available for Android 8.0 devices and above
  # adaptive_icon_monochrome: "" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/elixir.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/elixir.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/elixir.png"
